name: Create Detection Rule
description: Create a new detection rule
title: "[CREATE] "
labels: ["detection-rule", "create"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Create a New Detection Rule
        
        Use this form to create a new detection rule for the SIEM correlation engine.
        
        **What happens next:**
        1. Fill out this form with your detection rule details
        2. Submit the issue
        3. A workflow will automatically extract the information
        4. A pull request will be created with your rule in YAML format
        5. The team will review and approve the PR
        6. Once merged, the rule will be added to `SIEM/Correlation Rules/`
        
        **Note:** Leave "Modified By/Date" and "Detection Query Before" fields empty for new rules.
  
  - type: input
    id: rule-name
    attributes:
      label: Rule Name
      description: Provide a descriptive name for the detection rule
      placeholder: e.g., Suspicious PowerShell Execution
    validations:
      required: true

  - type: dropdown
    id: rule-status
    attributes:
      label: Rule Status
      description: Select the desired status for this detection rule
      options:
        - Disabled-PreProd
        - Enabled-PreProd
        - Disabled-Prod
        - Enabled-Prod
      default: 0
    validations:
      required: true

  - type: textarea
    id: rule-description
    attributes:
      label: Rule Description
      description: Describe what this detection rule should detect
      placeholder: Provide a detailed description of the detection rule
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: References
      description: Provide URL links to additional information, one per line (leave empty for NULL)
      placeholder: |
        https://example.com/threat-intel
        https://example.com/documentation
      render: text
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Author & Modification Information

  - type: input
    id: author-by
    attributes:
      label: Author
      description: Enter your name or GitHub username
      placeholder: Your name
    validations:
      required: true

  - type: input
    id: author-date
    attributes:
      label: Author Date
      description: Enter today's date (YYYY-MM-DD). This will be the creation date for the rule.
      placeholder: YYYY-MM-DD (e.g., 2025-12-01)
    validations:
      required: true

  - type: input
    id: modified-by
    attributes:
      label: Modified By
      description: Enter the name of the user modifying an existing rule (leave empty for NULL)
      placeholder: Your name, the one modifying the rule
    validations:
      required: false

  - type: input
    id: modified-date
    attributes:
      label: Modified Date
      description: Enter the date the rule was modified (leave empty for NULL)
      placeholder: YYYY-MM-DD or NULL
    validations:
      required: false      

  - type: textarea
    id: tags
    attributes:
      label: MITRE ATT&CK Mapping
      description: Provide the MITRE ATT&CK technique ID(s) and tactic(s), one per line
      placeholder: |
        attack.T1059
        attack.T1071
      render: text
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Data Sources & Detection Logic
  
  - type: checkboxes
    id: log-source-vendor
    attributes:
      label: Vendor Data Sources
      description: Select vendor data source(s) or specify custom vendor below
      options:
        - label: Microsoft 365 (O365)
        - label: AWS
        - label: Azure
        - label: Google Cloud Platform (GCP)
        - label: Palo Alto Networks
        - label: Cisco
        - label: Fortinet
        - label: CrowdStrike
        - label: SentinelOne
        - label: Okta
        - label: Other (specify below)
    validations:
      required: false

  - type: input
    id: log-source-vendor-custom
    attributes:
      label: Custom Vendor (if Other selected)
      description: If you selected "Other" above, specify the vendor name here
      placeholder: e.g., Custom Vendor Name
    validations:
      required: false
  
  - type: textarea
    id: log-source-service
    attributes:
      label: Service Data Sources
      description: What service data sources should be used?
      placeholder: e.g., Audit Logs, VPC Flow Logs, DNS Logs
    validations:
      required: true

  - type: textarea
    id: detection-query-before
    attributes:
      label: Detection Query Before
      description: For modifications only - Enter the previous/existing query. Leave empty for new rules.
      placeholder: Previous query (leave empty if this is a new rule)
    validations:
      required: false

  - type: textarea
    id: detection-query-after
    attributes:
      label: Detection Query After
      description: Enter the new/updated query that should trigger this detection
      placeholder: Enter the detection query
    validations:
      required: true

  - type: textarea
    id: detection-query-condition
    attributes:
      label: Detection Query Condition
      description: Describe the conditions that should trigger this detection
      placeholder: Trigger on the first event which matches the specified query
    validations:
      required: true

  - type: textarea
    id: detection-query-suppress
    attributes:
      label: Detection Query Suppress
      description: Enter the suppress criteria for this detection (leave empty for NULL)
      placeholder: Suppress for 15 minutes
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Severity & Response
  
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Select the severity level for this detection rule
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: textarea
    id: outcome
    attributes:
      label: Outcome
      description: Describe the expected outcome of this detection rule
      placeholder: Alert - No investigation required
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Review Schedule

  - type: input
    id: review-last-reviewed
    attributes:
      label: Review Last Reviewed
      description: Enter today's date (YYYY-MM-DD). This is the date the rule was created or last modified.
      placeholder: YYYY-MM-DD (e.g., 2025-12-01)
    validations:
      required: true

  - type: input
    id: review-next-review
    attributes:
      label: Review Next Review
      description: Enter the next review date (YYYY-MM-DD). This should be one year after the Review Last Reviewed date.
      placeholder: YYYY-MM-DD (e.g., 2026-12-01)
    validations:
      required: true

  - type: input
    id: expiry-date
    attributes:
      label: Expiry Date
      description: Enter the expiry date (leave empty for NULL)
      placeholder: YYYY-MM-DD or NULL
    validations:
      required: false
