name: Detection Rule Request Form
description: Request a new detection rule or modification to an existing rule
title: "[DETECTION] "
labels: ["detection-rule"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a detection rule!
  
  - type: input
    id: rule-name
    attributes:
      label: Rule Name
      description: Provide a descriptive name for the detection rule
      placeholder: e.g., Suspicious PowerShell Execution
    validations:
      required: true

  - type: dropdown
    id: rule-status
    attributes:
      label: Rule Status
      description: Select the desired status for this detection rule
      options:
        - Enabled-PreProd
        - Disabled-PreProd
        - Enabled-Prod
        - Disabled-Prod
    validations:
      required: true

  - type: textarea
    id: rule-description
    attributes:
      label: Rule Description
      description: Describe what this detection rule should detect
      placeholder: Provide a detailed description of the detection rule
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: References
      description: Provide URL links to additional information, one per line (leave empty for NULL)
      placeholder: |
        https://example.com/threat-intel
        https://example.com/documentation
      render: text
    validations:
      required: false

  - type: input
    id: author
    attributes:
      label: Author
      description: Enter your name or GitHub username
      placeholder: Your name
    validations:
      required: true

  - type: input
    id: modified
    attributes:
      label: Modified By
      description: Enter the name of the user modifying an existing rule (leave empty if not applicable)
      placeholder: Leave empty for NULL
    validations:
      required: false

  - type: input
    id: date-created
    attributes:
      label: Date Created
      description: Enter the date the rule was created (this should only be set once and never modified)
      placeholder: YYYY-MM-DD
    validations:
      required: true

  - type: textarea
    id: tags
    attributes:
      label: MITRE ATT&CK Mapping
      description: Provide the MITRE ATT&CK technique ID(s) and tactic(s), one per line
      placeholder: |
        attack.T1059
        attack.T1071
      render: text
    validations:
      required: false
  
  - type: textarea
    id: log-source-vendor
    attributes:
      label: Vendor Data Sources
      description: What vendor data sources should be used?
      placeholder: e.g., O365, AWS
    validations:
      required: true
  
  - type: textarea
    id: log-source-service
    attributes:
      label: Service Data Sources
      description: What service data sources should be used?
      placeholder: e.g., Audit Logs, VPC Flow Logs, DNS Logs
    validations:
      required: true

  - type: textarea
    id: detection-query-before
    attributes:
      label: Detection Query Before
      description: Describe the conditions or indicators that should trigger this detection
      placeholder: Provide specific criteria, patterns, or indicators
    validations:
      required: true

  - type: textarea
    id: detection-query-after
    attributes:
      label: Detection Query After
      description: Describe the conditions or indicators that should trigger this detection
      placeholder: Provide specific criteria, patterns, or indicators
    validations:
      required: true

  - type: textarea
    id: detection-query-condition
    attributes:
      label: Detection Query Condition
      description: Describe the conditions or indicators that should trigger this detection
      placeholder: Provide specific criteria, patterns, or indicators
    validations:
      required: true

  - type: textarea
    id: detection-query-suppress
    attributes:
      label: Detection Query Suppress
      description: Describe the conditions or indicators that should trigger this detection
      placeholder: Provide specific criteria, patterns, or indicators
    validations:
      required: true
  
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Select the severity level for this detection rule
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: textarea
    id: outcome
    attributes:
      label: Outcome
      description: Describe the expected outcome of this detection rule
      placeholder: Alert - No investigation required
    validations:
      required: true

  - type: input
    id: review-last-reviewed
    attributes:
      label: Review Last Reviewed
      description: Enter the last reviewed date
      placeholder: YYYY-MM-DD
    validations:
      required: false

  - type: input
    id: review-next-review
    attributes:
      label: Review Next Review
      description: Enter the next review date
      placeholder: YYYY-MM-DD
    validations:
      required: false

  - type: input
    id: expiry-date
    attributes:
      label: Expiry Date
      description: Enter the expiry date or leave empty for NULL
      placeholder: YYYY-MM-DD or NULL
    validations:
      required: false
